# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Runhui Blog
subtitle: ''
description: ''
keywords:
author: Runhui Miao
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://runhuimiao.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: 'git'
  repo: https://github.com/runhuimiao/runhuimiao.github.io.git
  branch: master

# hexo-word-counter
# https://github.com/next-theme/hexo-word-counter
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false
  awl: 4
  wpm: 275
  suffix: "mins."


# Extensions
## Plugins: https://hexo.io/plugins/
plugins: hexo-generator-sitemap
## Themes: https://hexo.io/themes/
theme: next
theme_config:
  scheme: Mist
  language: zh-Hans
  local_search:
    enable: true
    trigger: auto
  # Reading progress bar
  reading_progress:
    enable: true
    # Available values: top | bottom
    position: bottom
  menu:
    home: / || home  //首页
    about: /about/ || user  //关于
    tags: /tags/ || tags  //标签
    # categories: /categories/ || th   //分类
    archives: /archives/ || archive //归档
    # schedule: /schedule/ || calendar   //日程表
    sitemap: /sitemap.xml || sitemap   //站点地图
  menu_settings:
    icons: true   # 显示图标
    badges: true  # 显示统计信息
  footer:
    counter: true
    powered: false
  gitalk:
    enable: true
    github_id: runhuimiao
    repo: runhuimiao.github.io
    client_id: 6d3d0187e9d0209a7853
    client_secret: ec2b24a1c30cfb298e9665d16f00b28e289cfba6
    admin_user: [runhuimiao]
    language: zh-CN
  busuanzi_count:
    enable: true
  symbols_count_time:
    item_text_total: true
  # Show previous post and next post in post footer if exists
  # Available values: left | right | false
  post_navigation: right
  # `Follow me on GitHub` banner in the top-right corner.
  github_banner:
    enable: true
    permalink: https://github.com/runhuimiao
  back2top:
    # Scroll percent label in b2t button.
    scrollpercent: true

# hexo-generator-searchdb
search:
  path: search.xml
  field: post
  format: html
  limit: 100
